NetAutoMgmt/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('account/', include('users.urls')),
]

main_app/urls.py
from django.contrib import admin
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path
from . import views
from .api import views as api_views

app_name = 'main_app'
urlpatterns = [
    path('api/sites/', api_views.SitesListCreateAPIView.as_view(), name='sites_rest_api'),
    path('api/sites/<uuid>', view=api_views.SitesRetrieveUpdateDestroyAPIView.as_view(),
            name='sites_rest_api'),
    path('api/devices/', api_views.DevicesListCreateAPIView.as_view(), name='devices_rest_api'),
    path('api/devices/<uuid>', api_views.DevicesRetrieveUpdateDestroyAPIView.as_view(),
            name='devices_rest_api'),
    path('', views.HomeTemplateView.as_view(), name='home'),
    path('sites', views.SitesListView.as_view(), name='viewsites'),
    path('sites/<int:pk>', views.SitesDetailView.as_view(), name='sitesdetail'),
    path('updatesite/<int:pk>', views.SiteUpdateView.as_view(), name='updatesite'),
    path('deletesite/<int:pk>', views.SiteDeleteView.as_view(), name='deletesite'),
    path('devices', views.DeviceListView.as_view(), name='viewdevices'),
    path('create/', views.SiteCreateView.as_view(), name='createsite'),
    path('create_device/', views.DeviceCreateView.as_view(), name='createdevice'),
    path('devices/<int:pk>', views.DeviceDetailView.as_view(), name='devicedetail'),
    path('devices/config/<int:pk>', views.DeviceConfigDetailView.as_view(), name='deviceconfig'),
    path('devices/script/<int:pk>', views.DeviceScriptDetailView.as_view(), name='devicescript'),
    path('updatedevice/<int:pk>', views.DeviceUpdateView.as_view(), name='updatedevice'),
    path('deletedevice/<int:pk>', views.DeviceDeleteView.as_view(), name='deletedevice'),
    path('deleteconfig/config/<int:pk>', views.DeviceConfigDeleteView.as_view(), name='deleteconfig'),
    path('devices/syncconfig/<deviceip>&<deviceid>', views.sync_configuration, name='configsync'),
    path('devices/platformsync/<deviceip>&<deviceid>', views.get_platform_detail, name='platformsync'),
    path('search/', views.device_search_function, name='search'),
    path('devices/syncvlans/<deviceip>&<deviceid>', views.sync_device_vlans, name='vlanssync'),
    path('devices/tasks/vlanchange/<deviceip>&<deviceid>', views.port_vlan_assignment, name='vlanchange'),

]

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
# from .views import register

app_name = 'users'
urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view(template_name='users/login.html'),
                    name='login'),
    path('logout/', auth_views.LogoutView.as_view(
                    template_name='users/logout.html'),
                    name='logout'),
]

main_app/forms.py
from django import forms
from .models import Sites, Devices


class SitesForm(forms.ModelForm):
    """
    this form class will be used to customize the form widgets based on custom
    css stylesheet
    """
    class Meta():
        model = Sites
        fields = ('site_name', 'site_location', 'site_address',
                    'site_poc_name', 'site_poc_number')
        widgets = {
                    'site_name': forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'Site Name'}),
                    'site_location':forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'Location'}),
                    'site_address':forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'Address'}),
                    'site_poc_name':forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'Point of Contact'}),
                    'site_poc_number':forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'POC Number'}),
        }


class DeviceForm(forms.ModelForm):
    """
    this form class will be used to customize the form widgets based on custom
    css stylesheet
    """

    class Meta():
        model = Devices
        fields = ('device_name', 'device_ip', 'vendor', 'device_type',
                    'operating_system', 'device_username',
                    'device_password','site')
        widgets = {
                    'device_name': forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'Device Name'}),
                    'device_ip':forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'IP Address'}),
                    'vendor':forms.Select(attrs={
                    'class':'mycustom-select', 'id':'vendor-select'}),
                    'device_type':forms.Select(attrs={
                    'class':'mycustom-select', 'id':'device-type-select'}),
                    'operating_system':forms.Select(attrs={
                    'class':'mycustom-select', 'id':'os-select'}),
                    'device_username':forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'username'}),
                    'device_password':forms.TextInput(attrs={
                    'class':'textinputclass', 'type':'password',
                    'placeholder': 'password'}),
                    'site':forms.Select(attrs={
                    'class':'mycustom-select', 'id':'site-select'}),
        }

main_app/api/views.py
from rest_framework.generics import (
    ListCreateAPIView,
    RetrieveUpdateDestroyAPIView)
from rest_framework.permissions import IsAuthenticated

from ..models import Sites, Devices

from .serializers import SitesSerializer, DevicesSerializer

class SitesListCreateAPIView(ListCreateAPIView):

    queryset = Sites.objects.all()
    permission_classes = (IsAuthenticated, )
    serializer_class = SitesSerializer
    lookup_field = "uuid" # Dont use the model id or pk for API


class SitesRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):

    queryset = Sites.objects.all()
    permission_classes = (IsAuthenticated, )
    serializer_class = SitesSerializer
    lookup_field = 'uuid' # Dont use the model id or pk for API


#Devices views

class DevicesListCreateAPIView(ListCreateAPIView):

    queryset = Devices.objects.all()
    permission_classes = (IsAuthenticated, )
    serializer_class = DevicesSerializer
    lookup_field = "uuid" # Dont use the model id or pk for API


class DevicesRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):

    queryset = Devices.objects.all()
    permission_classes = (IsAuthenticated, )
    serializer_class = DevicesSerializer
    lookup_field = 'uuid' # Dont use the model id or pk for API

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic import (TemplateView, ListView, DetailView,
                                    CreateView, UpdateView, DeleteView)
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from requests.exceptions import ConnectionError
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.db.models import Q as Query
from netmiko.ssh_exception import (AuthenticationException,
                                    NetMikoTimeoutException)
from paramiko.ssh_exception import SSHException
from . import models
from .forms import SitesForm, DeviceForm
from script.pullconfig_script import (sync_platform,
                                        sync_device_configuration,
                                        vlan_change,
                                        get_device_vlans,
                                        )
from script.api_scripts import AuthenticationError

# Create your views here.

class HomeTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'main_app/home.html'
    context_object_name = 'home_page'

# Sites CBVs
class SitesListView(LoginRequiredMixin, ListView):
    """ CBV to display the created sites"""
    context_object_name = 'sites'
    model = models.Sites
    paginate_by = 10


class SitesDetailView(LoginRequiredMixin, DetailView):
    """ CBV to display site details"""
    context_object_name = 'sites_detail'
    model = models.Sites
    template_name = 'main_app/sites_detail.html'


class SiteCreateView(LoginRequiredMixin, CreateView):
    """ CBV form to create new sites"""
    form_class = SitesForm
    model = models.Sites

    def form_valid(self, form):
        sitename = form.cleaned_data.get('site_name')
        messages.add_message(
            self.request, messages.SUCCESS, f'Site {sitename} created!')
        return super().form_valid(form)


class SiteUpdateView(LoginRequiredMixin, UpdateView):
    """ CBV form to update site details"""
    # fields = ('site_name', 'site_poc_name', 'site_poc_number')
    form_class = SitesForm
    model = models.Sites

    def form_valid(self, form):
        sitename = form.cleaned_data.get('site_name')
        messages.add_message(
            self.request, messages.SUCCESS,
            f'Site detail for {sitename} updated!')
        return super().form_valid(form)


class SiteDeleteView(LoginRequiredMixin, DeleteView):
    """CBV delete form to delete sites"""
    context_object_name = 'site'
    model = models.Sites
    success_url = reverse_lazy('main_app:viewsites')


# Devices CBVs
class DeviceListView(LoginRequiredMixin, ListView):
    "CBV to display created devices in the db"
    context_object_name = 'devices'
    model = models.Devices
    paginate_by = 10



class DeviceDetailView(LoginRequiredMixin, DetailView):
    "CBV to display device detail information"
    context_object_name = 'device_detail'
    model = models.Devices
    template_name = 'main_app/devices_detail.html'


class DeviceCreateView(LoginRequiredMixin, CreateView):
    "CBV form to create new devices"
    # fields = ('device_name', 'device_ip',
    #             'vendor',  'site')
    form_class = DeviceForm
    model = models.Devices

    def form_valid(self, form):
        devicename = form.cleaned_data.get('device_name')
        messages.add_message(
            self.request, messages.SUCCESS, f'Device {devicename} created!')
        return super().form_valid(form)


class DeviceUpdateView(LoginRequiredMixin, UpdateView):
    "CBV form to update device details"
    # fields = ('device_name', 'device_ip',
    #             'site', 'vendor')
    form_class = DeviceForm
    model = models.Devices

    def form_valid(self, form):
        devicename = form.cleaned_data.get('device_name')
        messages.add_message(
            self.request, messages.SUCCESS, f'Update to {devicename} done!')
        return super().form_valid(form)


class DeviceDeleteView(LoginRequiredMixin, DeleteView):
    "CBV to delete devices"
    context_object_name = 'device'
    model = models.Devices
    success_url = reverse_lazy('main_app:viewdevices')


class DeviceConfigDetailView(LoginRequiredMixin, DetailView):
    "CBV display device saved configuration"
    context_object_name = 'deviceconfig'
    model = models.DeviceDetail
    template_name = 'main_app/deviceconfig_view.html'


class DeviceScriptDetailView(LoginRequiredMixin, DetailView):
    "CBV display device saved custom scripts"
    context_object_name = 'devicescript'
    model = models.DeviceDetail
    template_name = 'main_app/devicescript_view.html'

class DeviceConfigDeleteView(LoginRequiredMixin, DeleteView):
    "CBV to delete device configurations from the db."
    context_object_name = 'deviceconfig'
    model = models.DeviceDetail
    success_url = reverse_lazy('main_app:viewdevices')



def get_platform_detail(request, deviceip, deviceid):
    """
    get_platform_detail takes 3 arguements (request, ip, device_db_id)
    function will then call the population function sync_platform under
    pullconfig_script module, which will then call the OS class method
    get_platform_detail under api_scripts module.

    platform details will be returned by get_platform_detail in a dictionary
    to be populated in the DB by sync_platform function using the
    sync_platform_attributes method in class DataBaseActions under
    pullconfig_script module in the script directory.
    """
    success_url = f'devices/{deviceid}'
    try:
        sync_platform(deviceip, deviceid)
        messages.add_message(
            request, messages.SUCCESS, f'platform details synced')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except ConnectionError:
        messages.add_message(
            request, messages.ERROR, f'IP {deviceip} unreachable')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except AuthenticationError:
        messages.add_message(
            request, messages.ERROR, 'Invalid username and password')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except AuthenticationException:
        messages.add_message(
            request, messages.ERROR, 'Invalid username and password')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except NetMikoTimeoutException:
        messages.add_message(
            request, messages.ERROR, 'Connection request timeout')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except SSHException:
        messages.add_message(
            request, messages.ERROR, 'Unable to establish SSH session, SSH enabled?')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except Exception as error:
        messages.add_message(
            request, messages.WARNING, f'Unknown error has occurred: {error}')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))



@login_required
def sync_configuration(request, deviceip, deviceid):
    """
    function will pass device ip and device db id to the population script
    function sync_device_configuration under module pullconfig_script
    which will call the method in the OS class under api_scripts module
    to pull the running configuration of the device and return it in a
    dictionary to be handled by sync_device_configuration function which
    will perform a DB update function to update the configuration in the db.
    """
    success_url = f'devices/{deviceid}'
    try:
        user = request.user
        sync_device_configuration(deviceip, deviceid, user)
        messages.add_message(
            request, messages.SUCCESS, f'Configuration has been synced')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except ConnectionError:
        messages.add_message(
            request, messages.ERROR, f'IP {deviceip} unreachable')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except AuthenticationError:
        messages.add_message(
            request, messages.ERROR, 'Invalid username and password')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except AuthenticationException:
        messages.add_message(
            request, messages.ERROR, 'Invalid username and password')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except NetMikoTimeoutException:
        messages.add_message(
            request, messages.ERROR, 'Connection request timeout')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except SSHException:
        messages.add_message(
            request, messages.ERROR, 'Unable to establish SSH session, SSH enabled?')
        return HttpResponseRedirect(reverse(f'main_app:devicedetail',
                                        kwargs={'pk': deviceid}))
    except Exception as error:
        messages.add_message(
            request, messages.WARNING, f'Unknown error has occurred: {error}')

main_app/templates/main_app/devices_list.html
{% extends 'main_app/main_app_base.html' %}
{%block content %}

<div class="" style="width: 90%; margin-left: auto; margin-right: auto;">
  <a class="" href="{% url 'main_app:createdevice' %}">
    <input class="float-right" id="btn-save" type="submit" value="Create">
  </a>
  <table id="device-table1">
    <table  class="ctable ctable-noSideBorder">
      <thead class="layout">

          <th>Device Name</th>
          <th>Device IP</th>
          <th>Site</th>

      </thead>
      <tbody>
        {% for device in devices %}
        <tr>
            <td><a href="devices/{{device.id}}">{{device.device_name}}</a></td>
            <td>{{device.device_ip}}</td>
            <td><a href="sites/{{ device.site.id }}">{{device.site.site_name}}</a></td>
        </tr>
        {%endfor%}
      </tbody>

    </table>
  </table>
</div>
<div>
  {% if is_paginated %}
    {% if page_obj.has_previous %}
      <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    {%endif%}
    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
        <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
      {%endif%}
    {%endfor%}
    {% if page_obj.has_next %}
      <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
      <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
    {%endif%}
  {% endif %}
</div>

{%endblock content %}

main_app/templates/main_app/main_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    {% if home_page %}
    <title>AutoNet - Home</title>
    {% elif sites %}
    <title>AutoNet - Sites</title>
    {%elif devices%}
    <title>AutoNet - Device Inventory</title>
    {%elif device_detail%}
    <title>Device - {{device_detail.device_name}}</title>
    {%elif deviceconfig%}
    <title>{{deviceconfig.device_id.device_name}} - Config</title>
    {%else%}
    <title>AutoNet</title>
    {%endif%}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/form.css' %}">
  </head>
  <body class="bg-light" style="font-family: sans-serif;">

    <header>
      <!-- <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> -->
    <div class="mb-4">


      <nav class="navbar navbar-expand-lg navbar-dark fixed-top custom_navbar" style="background-color: #3d3d3d; font-size: 14px; font-family: 'Source Sans Pro' !important;" >
        <div class="navbar-brand">

        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main_app:home' %}">
                <div class="nav-icon">
                  <i id="home-icon" class="material-icons">home</i>
                </div>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main_app:viewsites' %}">
                <div class="nav-icon">
                  <i id="sites-icon" class="material-icons">domain</i>
                </div>  <span class="sr-only">(current)</span></a>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main_app:viewdevices' %}">
                <div class="nav-icon">
                  <i id="devices-icon" class="material-icons">storage</i>
                </div></a>
              </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'admin:index' %}">
                <div class="nav-icon">
                  <i id="admin-icon" class="material-icons">settings</i>
                </div></a>
              </a>
            </li>
          </ul>
          <div class="">
            {% if user.is_authenticated%}
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <a class="nav-link" href="#">Welcome, {{user.username}}</a>
              </li>
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
              </li>
            </ul>
            {% endif %}
          </div>
          <form class="form-inline my-2 my-lg-0" action="{% url 'main_app:search'%}" method="get">
              <input class="form-control ml-2 mr-sm-2 " type="search"  name="item" style="height: 30px;"placeholder="Hostname or IP" aria-label="Search">
              <button id="btn-search" class="btn_class" type="submit" >Search</button>
        </form>

          <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form> -->
        </div>
      </nav>
    </div>
    </header>
    <div class="container" style="padding: 16px 0px;">
      {% if messages %}
        {% for message in messages %}
            <div class="custom_alert" id="custom_alert_{{message.tags}}" role="alert">
             {{message}}
            </div>
        {% endfor %}
      {% endif%}
    </div>
    <br>
    {%block content %}

    {%endblock content %}

    <!-- Here goes the page footer -->

      <!-- <footer class="page-footer font-small special-color-dark pt-4">
        <div class="container">
          <p>Created by Francisco</p>
        </div>
      </footer> -->
    <script type="text/javascript" href="{% static 'js/main.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
  </body>
</html>

main_app/templates/main_app/results.html
{% extends 'main_app/main_app_base.html' %}

{%block content %}
    {% csrf_token %}
    <div class="" style="width: 90%; margin-left: auto; margin-right: auto;">
    {% if results %}
        <h3>Search result:</h3>
        <table class="ctable ctable-noSideBorder">
            <thead class="layout">
                <th>Host Name</th>
                <th>IP Address</th>
                <th>Location</th>
            </thead>
            {%for result in results%}
                <tr>
                    <td><a href="{% url 'main_app:devicedetail' pk=result.id%}">{{result.device_name}}</a> </td>
                    <td>{{result.device_ip}}</td>
                    <td><a href="{% url 'main_app:sitesdetail' pk=result.site.id%}">{{result.site.site_name}}</a></td>
                </tr>
            {%endfor%}
            </table>

    {%else%}
        <h2>No Match found</h2>
    {%endif%}
    </div>
{%endblock content %}

main_app/templates/main_app/sites_confirm_delete.html
{% extends 'main_app/main_app_base.html' %}
{% load crispy_forms_tags %}

{%block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    <br>
    <p>Are you sure you want to delete {{site.site_name}}?</p>
    <a href="{% url 'main_app:sitesdetail' pk=site.id%}"><input class="btn-class" id="btn-cancel" type="button" value="Cancel"></a>
    <input class="btn-class" id="btn-delete" type="submit" value="Delete">

  </form>
</div>

{%endblock content %}

main_app/templates/main_app/sites_detail.html
{% extends 'main_app/main_app_base.html' %}


{%block content %}
<div class="" style="width: 90%; margin-left: auto; margin-right: auto;">
  <div class="float-right">
    <a href="{% url 'main_app:updatesite' pk=sites_detail.id%}">
      <button class="btn-class" id="btn-edit" type="submit">Edit</button>
    </a>
    <a href="{% url 'main_app:deletesite' pk=sites_detail.id%}">
      <button class="btn-class" id="btn-delete" type="submit">Delete</button>
    </a>
  </div>
  <h2>Site Details</h2>
  <br>
  <table id="device-table1">
    <table class="ctable ctable-noSideBorder">
      <thead  class="layout">
        <th>Site Name</th>
        <th>Location</th>
        <th>Address</th>
        <th>Point of Contact</th>
        <th>Contact Number</th>
      </thead>
      <tbody>
        <tr>
          <td>{{sites_detail.site_name}}</td>
          <td>{{sites_detail.site_location}}</td>
          <td>{{sites_detail.site_address}}</td>
          <td>{{sites_detail.site_poc_name}}</td>
          <td>{{sites_detail.site_poc_number}}</td>
        </tr>
      </tbody>
    </table>
  </table>

  <br>
  <h2>Registered devices</h2>
  <br>
  <table id="device-table1">
    <table class="ctable ctable-noSideBorder">
      <thead  class="layout">
        <th>Device Name</th>
        <th>Device IP</th>
      </thead>
      <tbody>
        {% for device in sites_detail.devices.all %}
          <tr>
            <td><a href="{% url 'main_app:devicedetail' pk=device.id%}">{{device.device_name}}</a></td>
            <td>{{device.device_ip}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </table>

</div>
{%endblock content %}

main_app/templates/main_app/sites_list.html
{% extends 'main_app/main_app_base.html' %}


{%block content %}
  <div class="" style="width: 90%; margin-left: auto; margin-right: auto;">
      <a href="{% url 'main_app:createsite' %}">
        <input class="btn-class float-right" id="btn-save" type="submit" value="Create">
      </a>
      <table id="device-table1">
        <table class="ctable ctable-noSideBorder">
          <thead class="layout">
            <th>Site Name</th>
            <th>Location</th>
            <th>Point of Contact</th>
          </thead>
          <tbody>
            {% for site in sites %}
            <tr >
                <td><a href="sites/{{ site.id }}">{{site.site_name}}</a></td>
                <td>{{site.site_location}}</td>
                <td>{{site.site_poc_name}}</td>
            </tr>
            {%endfor%}
          </tbody>
        </table>
      </table>

      {% if is_paginated %}
        {% if page_obj.has_previous %}
          <a class="btn btn-outline-info mb-4" href="?page=1">First</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.previous_page_number }}">Previous</a>
        {%endif%}
        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <a class="btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3'%}
            <a class="btn btn-outline-info mb-4" href="?page={{num}}">{{num}}</a>
          {%endif%}
        {%endfor%}
        {% if page_obj.has_next %}
          <a class="btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
          <a class="btn btn-outline-info mb-4" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
        {%endif%}
      {% endif %}
    </div>
{%endblock content %}