NetAutoMgmt/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('account/', include('users.urls')),
]

users/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
# from .views import register

app_name = 'users'
urlpatterns = [
    path('login/',
        auth_views.LoginView.as_view(template_name='users/login.html'),
                    name='login'),
    path('logout/', auth_views.LogoutView.as_view(
                    template_name='users/logout.html'),
                    name='logout'),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1',
                    'password2']

					
class CustomLoginForm(forms.ModelForm):

    class Meta:
	    model = User
        fields = ('username', 'password')
        widgets = {
                    'username': forms.TextInput(attrs={
                    'class':'textinputclass', 'placeholder': 'Username'}),
                    'password':forms.TextInput(attrs={
                    'class':'textinputclass', 'type':'password', placeholder': 'Password'})}

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm


# Create your views here.
# 
# def register(request):
#     if request.method == 'POST':
#         form = UserRegisterForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             messages.add_message(
#                        request, messages.SUCCESS,
#                        f'User {username} created!')
#             return redirect('main_app:home')
#     else:
#         form = UserRegisterForm()
#     return render(request, 'users/register.html', {'form':form})

users/templates/users/login.html
{% extends 'users/login_base.html' %}
{% load crispy_forms_tags %}

{% block content %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/login_css.css' %}">
<div id="container">
  <div class="login-header-color" >
    <h1 id="brand-name" ><strong>AutoNet</strong></h1>
  </div>
  <img id="user-logo" src="{% static 'users/login.png' %}" alt="">
  <form id="login-form" method="POST">
    <div class="form-group">
      <div id="content" class="colm">
      <fieldset id="custom-fieldset">
          <legend><strong>Log In</strong></legend>
      </fieldset>
        <div id="form-div">
          {% csrf_token %}
            {{ form.as_p }}
        </div>
        <div class="submit-row">
          <input id="login-btn" type="submit" value="Login">
        </div>
        <input type="hidden" name="next" value="{{ next }}">
        <br class="clear">
        <br class="clear">
        <fieldset style="padding: 10px;">
        <br class="clear">
        <small>
         <a id="forgot-ps-text" class="text-muted" href="#">Forgot password?</a>
        </small>
        </fieldset>
      </div>
    </div>
  </form>
</div>
{% endblock %}

users/templates/users/login_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/login.css">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <title></title>
  </head>
  <body style="font-family: Sans-serif;" class="login" data-admin-utc-offset="0">
        <!-- Tabs Titles -->
        <!-- Form -->
    <div class="container">

    </div>
    {% block content %}
    {% endblock content %}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

<!------ Include the above in your HEAD tag ---------->

users/templates/users/logout.html
{% extends 'users/login_base.html' %}

{%block content%}
<div id="container" style="padding: 16px">
  <div>
  <h3 style="font-size: 16px;">You have now logged out.</h3>
  <br class="clear">
  <a href="{% url 'users:login'%}">Log in again?</a>
  </div>
</div>

{%endblock content %}

users/templates/users/register.html
{% extends 'main_app/main_app_base.html' %}
{% load crispy_forms_tags %}

{%block content %}
<div class="container jumbotron">
  <div class="content-section">
    <form class="" method="POST">
      {% csrf_token %}

      <fieldset>
        <legend class="border-bottom mb-4">Register</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Sign Up</button>
      </div>
    </form>
    <div class="border-top pt-3">
      <small class="text-muted">
        Already have an account? <a class="ml-2" href="#">Sign In</a>
      </small>
    </div>
  </div>
</div>
{% endblock content %}